/**
 * Semantic autocomplete ranker using all-MiniLM-L6-v2.
 *
 * Two-tier ranking:
 *   1. Precomputed view embeddings (viewEmbeddings.json, generated by
 *      scripts/train/gen_view_embeddings.py from ViewCollection.java).
 *      Only the query context is embedded at runtime — view vectors are free.
 *   2. Full pairwise embedding for non-view candidates (tables, macros) when
 *      the model is loaded.
 *
 * Regenerate the static index whenever views change:
 *   python3 scripts/train/gen_view_embeddings.py
 */

import viewEmbeddingsRaw from '../../data/viewEmbeddings.json';

const DIM = 384;

// ─── Static view index ────────────────────────────────────────────────────────

type ViewIndex = Map<string, Float32Array>;  // view name → L2-normalised embedding

let _viewIndex: ViewIndex | null = null;

function getViewIndex(): ViewIndex {
    if (_viewIndex) return _viewIndex;
    const idx: ViewIndex = new Map();
    const raw = viewEmbeddingsRaw as {
        dim: number;
        views: Record<string, { vec: number[] }>;
    };
    for (const [name, entry] of Object.entries(raw.views)) {
        idx.set(name, new Float32Array(entry.vec));
    }
    _viewIndex = idx;
    return idx;
}

// ─── MiniLM pipeline (lazy-loaded for full pairwise ranking) ──────────────────

let pipelinePromise: Promise<any> | null = null;
let _ready = false;

export function isReady(): boolean {
    return _ready;
}

export async function ensureLoaded(): Promise<void> {
    if (pipelinePromise) {
        await pipelinePromise;
        return;
    }
    pipelinePromise = (async () => {
        const { pipeline, env } = await import('@huggingface/transformers');
        env.allowLocalModels = false;
        env.useBrowserCache = true;
        const ext = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2', {
            dtype: 'q4',
            device: 'webgpu', // auto-falls-back to WASM
        });
        // Warmup — first inference compiles WASM/WebGPU kernel.
        await ext('warmup', { pooling: 'mean', normalize: true });
        _ready = true;
        return ext;
    })();
    await pipelinePromise;
}

async function getPipeline(): Promise<any> {
    await ensureLoaded();
    return pipelinePromise!;
}

// ─── Math helpers ─────────────────────────────────────────────────────────────

function cosine(a: Float32Array, b: Float32Array): number {
    // Both are already L2-normalised.
    let s = 0;
    for (let i = 0; i < a.length; i++) s += a[i] * b[i];
    return s;
}

function sliceRow(flat: Float32Array, i: number): Float32Array {
    return flat.subarray(i * DIM, (i + 1) * DIM);
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Embed a single query context string and return the L2-normalised vector.
 * Requires the model to be loaded (call ensureLoaded first or check isReady).
 */
async function embedQuery(queryContext: string): Promise<Float32Array | null> {
    if (!_ready) return null;
    const ext = await getPipeline();
    const out: any = await ext([queryContext], { pooling: 'mean', normalize: true });
    return sliceRow(out.data as Float32Array, 0);
}

/**
 * Re-sort `candidates` by semantic similarity to `queryContext`.
 *
 * Fast path (no model needed): if all candidates are known view names, scores
 * them against the precomputed view index — only the query context is embedded.
 *
 * Full path (model required): embeds both the query and all candidates.
 *
 * Returns the original order if the model isn't ready and no candidate has a
 * precomputed embedding.
 */
export async function rankCandidates(
    queryContext: string,
    candidates: string[],
): Promise<string[]> {
    if (candidates.length <= 1) return candidates;

    const viewIdx = getViewIndex();

    // Determine which candidates have precomputed embeddings.
    // `candidates` are displayText strings like "gc-pauses  (view)"; extract
    // the view name as the part before the first whitespace.
    const names = candidates.map(c => c.split(/\s/)[0].replace(/^"|"$/g, ''));
    const precomputed = names.map(n => viewIdx.get(n) ?? null);
    const allPrecomputed = precomputed.every(v => v !== null);

    if (allPrecomputed || _ready) {
        // Embed only the query context.
        const qVec = await embedQuery(queryContext);
        if (!qVec) {
            // Model not ready yet and we need it for a partial set.
            if (!allPrecomputed) return candidates;
        }

        if (allPrecomputed && qVec) {
            // Score all candidates from the static index.
            return candidates
                .map((c, i) => ({ c, s: cosine(qVec, precomputed[i]!) }))
                .sort((a, b) => b.s - a.s)
                .map(x => x.c);
        }

        if (_ready) {
            // Mixed: embed everything pairwise for candidates not in the index.
            const ext = await getPipeline();
            const inputs = [queryContext, ...candidates.map((_, i) =>
                precomputed[i] ? names[i] : candidates[i]
            )];
            const out: any = await ext(inputs, { pooling: 'mean', normalize: true });
            const flat: Float32Array = out.data;
            const ctxEmb = sliceRow(flat, 0);

            return candidates
                .map((c, i) => ({
                    c,
                    s: precomputed[i]
                        ? cosine(ctxEmb, precomputed[i]!)
                        : cosine(ctxEmb, sliceRow(flat, i + 1)),
                }))
                .sort((a, b) => b.s - a.s)
                .map(x => x.c);
        }
    }

    return candidates;
}
